<?php require_once __DIR__ . '/../src/partials.php';$pdo=db();$stats=$pdo->query("SELECT COUNT(*) products,COALESCE(SUM(current_stock),0) stock,COUNT(*) FILTER(WHERE current_stock<=min_stock) low FROM products WHERE active=TRUE")->fetch();$month=(int)date('m');$year=(int)date('Y');$out=$pdo->prepare("SELECT COALESCE(SUM(quantity),0) FROM stock_movements WHERE movement_type='OUT' AND EXTRACT(MONTH FROM created_at)=? AND EXTRACT(YEAR FROM created_at)=?");$out->execute([$month,$year]);$outQty=$out->fetchColumn();$rows=$pdo->query("SELECT TO_CHAR(months.month,'YYYY-MM') label,COALESCE(SUM(m.quantity),0) qty FROM generate_series(date_trunc('month',CURRENT_DATE)-interval '11 months',date_trunc('month',CURRENT_DATE),interval '1 month') months(month) LEFT JOIN stock_movements m ON m.movement_type='OUT' AND date_trunc('month',m.created_at)=months.month GROUP BY months.month ORDER BY months.month")->fetchAll();$top=$pdo->query("SELECT p.name,SUM(m.quantity) qty FROM stock_movements m JOIN products p ON p.id=m.product_id WHERE m.movement_type='OUT' AND m.created_at>=date_trunc('month',CURRENT_DATE)-interval '5 months' GROUP BY p.id,p.name ORDER BY qty DESC LIMIT 8")->fetchAll();page_start('แดชบอร์ด');?>
<div class="card" style="background:linear-gradient(135deg,#172554 0%,#312e81 52%,#4c1d95 100%);color:#fff;border:0;overflow:hidden;position:relative;margin-bottom:18px">
  <div style="position:absolute;width:240px;height:240px;border-radius:50%;right:-80px;top:-110px;background:rgba(255,255,255,.08)"></div>
  <div style="position:absolute;width:130px;height:130px;border-radius:50%;right:150px;bottom:-90px;background:rgba(34,211,238,.10)"></div>
  <div style="position:relative;display:flex;align-items:center;justify-content:space-between;gap:18px;flex-wrap:wrap">
    <div><div style="font-size:12px;color:#c7d2fe;font-weight:700;letter-spacing:.04em">WELCOME BACK</div><h3 style="font-size:24px;margin:3px 0 2px">สวัสดี, <?=h($_SESSION['user']['full_name'])?> 👋</h3><div style="color:#cbd5e1;font-size:12px">ภาพรวมคลังสินค้าและการเคลื่อนไหวของวันนี้</div></div>
    <div class="badge" style="background:rgba(255,255,255,.12);color:#fff;border:1px solid rgba(255,255,255,.16)">● ระบบออนไลน์</div>
  </div>
</div>
<div class="quick-grid">
  <a class="quick-action" href="/stock_in.php"><span class="quick-icon">＋</span><span><span class="quick-title">รับสินค้าเข้า</span><span class="quick-sub">เพิ่มสินค้าเข้าคลัง</span></span></a>
  <a class="quick-action" href="/stock_out.php"><span class="quick-icon">−</span><span><span class="quick-title">เบิกสินค้าออก</span><span class="quick-sub">บันทึกการเบิกจ่าย</span></span></a>
  <a class="quick-action" href="/products.php"><span class="quick-icon">▣</span><span><span class="quick-title">จัดการสินค้า</span><span class="quick-sub">เพิ่ม แก้ไข และดูสต๊อก</span></span></a>
  <a class="quick-action" href="/reports.php"><span class="quick-icon">▤</span><span><span class="quick-title">ดูรายงาน</span><span class="quick-sub">สรุปและ Export PDF/Excel</span></span></a>
</div>
<div class="grid">
  <div class="card stat-card"><div class="stat-head"><div><div class="muted">สินค้าทั้งหมด</div><div class="metric-sub">รายการในคลัง</div></div><div class="stat-icon">▣</div></div><div class="metric"><?=number_format($stats['products'])?></div></div>
  <div class="card stat-card"><div class="stat-head"><div><div class="muted">สินค้าคงเหลือรวม</div><div class="metric-sub">จำนวนหน่วยทั้งหมด</div></div><div class="stat-icon green">✓</div></div><div class="metric"><?=number_format($stats['stock'])?></div></div>
  <div class="card stat-card"><div class="stat-head"><div><div class="muted">ต่ำกว่าจุดขั้นต่ำ</div><div class="metric-sub">ควรตรวจสอบ / เติมสต๊อก</div></div><div class="stat-icon red">!</div></div><div class="metric low"><?=number_format($stats['low'])?></div></div>
  <div class="card stat-card"><div class="stat-head"><div><div class="muted">เบิกเดือนนี้</div><div class="metric-sub">ยอดสะสมเดือนปัจจุบัน</div></div><div class="stat-icon orange">↗</div></div><div class="metric"><?=number_format($outQty)?></div></div>
</div>
<div class="dashboard-grid">
  <div class="card chart-card" style="margin-top:0"><div class="chart-head"><div><h3>แนวโน้มการเบิกสินค้า 12 เดือน</h3><div class="muted">ดูปริมาณการเบิกย้อนหลังเพื่อช่วยวางแผนสต๊อก</div></div><span class="badge success-bg">12 เดือน</span></div><canvas id="monthlyChart"></canvas></div>
  <div class="card health-card" style="margin-top:0"><div class="health-head"><div><div class="health-title">⚠ สินค้าที่ควรเติมสต๊อก</div><div class="muted">รายการที่ต่ำกว่าจุดขั้นต่ำ</div></div><span class="badge danger-bg"><?=number_format($stats['low'])?> รายการ</span></div><div class="health-list">
<?php $lowRows=$pdo->query("SELECT name,current_stock,min_stock FROM products WHERE current_stock<=min_stock ORDER BY current_stock ASC,name ASC LIMIT 6")->fetchAll(); if(!$lowRows): ?><div class="health-empty">✓ สต๊อกอยู่ในระดับปกติ</div><?php else: foreach($lowRows as $lr): $min=max(1,(int)$lr['min_stock']); $pct=min(100,round(((int)$lr['current_stock']/$min)*100)); ?><div class="health-row"><div style="min-width:0;flex:1"><div class="health-name"><?=h($lr['name'])?></div><div class="progress-track"><div class="progress-bar" style="width:<?=$pct?>%;background:linear-gradient(90deg,#ef4444,#f59e0b)"></div></div></div><div class="health-stock"><?=number_format($lr['current_stock'])?> / <?=number_format($lr['min_stock'])?></div></div><?php endforeach; endif; ?></div></div>
</div>
<div class="card chart-card"><div class="chart-head"><div><h3>สินค้าที่มีการเบิกสูงสุดใน 6 เดือนล่าสุด</h3><div class="muted">ช่วยให้เห็นสินค้าที่มีการหมุนเวียนสูง</div></div><span class="badge success-bg">Top 8</span></div><canvas id="topChart"></canvas></div>
<div class="footer-note"><strong>Stock Management</strong> • ระบบจัดการคลังสินค้าออนไลน์ • อัปเดตข้อมูลจากฐานข้อมูลแบบเรียลไทม์</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>const monthly=<?=json_encode($rows,JSON_UNESCAPED_UNICODE)?>;const top=<?=json_encode($top,JSON_UNESCAPED_UNICODE)?>;new Chart(document.getElementById('monthlyChart'),{type:'line',data:{labels:monthly.map(x=>x.label),datasets:[{label:'จำนวนเบิก',data:monthly.map(x=>Number(x.qty)),tension:.35,fill:true,borderColor:'#4f46e5',backgroundColor:'rgba(79,70,229,.10)',pointBackgroundColor:'#4f46e5',pointRadius:3}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,grid:{color:'rgba(148,163,184,.16)'}},x:{grid:{display:false}}}}});new Chart(document.getElementById('topChart'),{type:'bar',data:{labels:top.map(x=>x.name),datasets:[{label:'จำนวนเบิก',data:top.map(x=>Number(x.qty)),backgroundColor:['#4f46e5','#2563eb','#0891b2','#10b981','#f59e0b','#f97316','#ec4899','#7c3aed'],borderRadius:8,barThickness:20}]},options:{responsive:true,indexAxis:'y',plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,grid:{color:'rgba(148,163,184,.16)'}},y:{grid:{display:false}}}}});</script><?php page_end();
