<?php require_once __DIR__ . '/../src/partials.php'; $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){ check_csrf(); $action=$_POST['action']??''; try {
 if($action==='save') { $id=(int)($_POST['id']??0); $code=trim($_POST['code']??''); $name=trim($_POST['name']??''); $unit=trim($_POST['unit']??'pcs'); $min=max(0,(int)($_POST['min_stock']??0)); if(!$code||!$name) throw new Exception('กรุณากรอกรหัสและชื่อสินค้า'); if($id){$s=$pdo->prepare('UPDATE products SET code=?,name=?,unit=?,min_stock=?,updated_at=CURRENT_TIMESTAMP WHERE id=?');$s->execute([$code,$name,$unit,$min,$id]);flash('success','แก้ไขข้อมูลสินค้าแล้ว');}else{$s=$pdo->prepare('INSERT INTO products(code,name,unit,min_stock) VALUES(?,?,?,?)');$s->execute([$code,$name,$unit,$min]);flash('success','เพิ่มสินค้าแล้ว');}}
 elseif($action==='delete') { require_admin(); $id=(int)$_POST['id']; $pdo->beginTransaction(); try { $s=$pdo->prepare('SELECT id FROM products WHERE id=? FOR UPDATE');$s->execute([$id]);if(!$s->fetchColumn()) throw new Exception('ไม่พบสินค้าที่ต้องการลบ'); $s=$pdo->prepare('DELETE FROM stock_movements WHERE product_id=?');$s->execute([$id]); $s=$pdo->prepare('DELETE FROM products WHERE id=?');$s->execute([$id]); $pdo->commit(); flash('success','ลบสินค้าและประวัติการเคลื่อนไหวของสินค้านี้ถาวรแล้ว'); } catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
 elseif($action==='toggle') { require_admin(); $id=(int)$_POST['id']; $s=$pdo->prepare('UPDATE products SET active=NOT active,updated_at=CURRENT_TIMESTAMP WHERE id=?');$s->execute([$id]);$s=$pdo->prepare('SELECT active FROM products WHERE id=?');$s->execute([$id]);$active=$s->fetchColumn();flash('success',$active?'เปิดใช้งานสินค้าแล้ว':'ปิดใช้งานสินค้าแล้ว');}
 header('Location:/products.php'.(!empty($_POST['show'])?'?show='.rawurlencode($_POST['show']):'')); exit;
} catch(Throwable $e){flash('danger','ดำเนินการไม่สำเร็จ: '.$e->getMessage());header('Location:/products.php');exit;}}
$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM products WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}
$q=trim($_GET['q']??'');$show=$_GET['show']??'active';
$where=[];$params=[];if($show==='active'){$where[]='active=TRUE';}elseif($show==='inactive'){$where[]='active=FALSE';}if($q!==''){$where[]='(code ILIKE ? OR name ILIKE ?)';$params[]='%'.$q.'%';$params[]='%'.$q.'%';}$sql='SELECT * FROM products'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY active DESC,name';$s=$pdo->prepare($sql);$s->execute($params);$items=$s->fetchAll();page_start('คลังสินค้า');
?><div class="card"><form class="actions"><input type="hidden" name="show" value="<?=h($show)?>"><input name="q" placeholder="ค้นหาด้วยรหัสหรือชื่อสินค้า" value="<?=h($q)?>"><button class="primary">ค้นหา</button><?php if($q):?><a class="button secondary" href="/products.php?show=<?=h($show)?>">ล้างค้นหา</a><?php endif;?><a class="button <?= $show==='active'?'success':'secondary'?>" href="/products.php?show=active">ใช้งาน</a><a class="button <?= $show==='inactive'?'warning':'secondary'?>" href="/products.php?show=inactive">ปิดใช้งาน</a><a class="button secondary" href="/products.php?show=all">ทั้งหมด</a></form></div>
<div class="card form-card" style="margin-top:18px"><h3><?= $edit?'แก้ไขสินค้า':'เพิ่มสินค้า'?></h3><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=h($edit['id']??0)?>"><div class="form-grid"><div><label>รหัสสินค้า</label><input name="code" value="<?=h($edit['code']??'')?>" required></div><div><label>ชื่อสินค้า</label><input name="name" value="<?=h($edit['name']??'')?>" required></div><div><label>หน่วย</label><input name="unit" value="<?=h($edit['unit']??'pcs')?>"></div><div><label>สต๊อกขั้นต่ำ</label><input type="number" name="min_stock" value="<?=h($edit['min_stock']??500)?>" min="0"></div></div><button class="primary"><?= $edit?'บันทึกการแก้ไข':'เพิ่มสินค้า'?></button><?php if($edit):?><a class="button secondary" href="/products.php?show=<?=h($show)?>">ยกเลิก</a><?php endif;?></form></div>
<div class="table-wrap"><table><tr><th>รหัส</th><th>สินค้า</th><th>หน่วย</th><th>คงเหลือ</th><th>ขั้นต่ำ</th><th>สถานะ</th><th>จัดการ</th></tr><?php foreach($items as $x):?><tr><td><?=h($x['code'])?></td><td><?=h($x['name'])?></td><td><?=h($x['unit'])?></td><td><?=number_format($x['current_stock'])?></td><td><?=number_format($x['min_stock'])?></td><td><?php if(!$x['active']):?><span class="badge secondary-bg">ปิดใช้งาน</span><?php elseif($x['current_stock']<=$x['min_stock']):?><span class="badge danger-bg">ต่ำกว่าขั้นต่ำ</span><?php else:?><span class="badge success-bg">ปกติ</span><?php endif;?></td><td class="actions"><a class="button secondary" href="?edit=<?=h($x['id'])?>&show=<?=h($show)?>">แก้ไข</a><?php if(is_admin()):?><form method="post" onsubmit="return confirm('<?= $x['active']?'ยืนยันการปิดใช้งานสินค้า?':'ยืนยันการเปิดใช้งานสินค้า?' ?>')"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=h($x['id'])?>"><input type="hidden" name="show" value="<?=h($show)?>"><button class="button <?= $x['active']?'warning':'success'?>" type="submit"><?= $x['active']?'ปิดใช้งาน':'เปิดใช้งาน'?></button></form><form method="post" onsubmit="return confirm('ยืนยันการลบสินค้าแบบถาวร? รายการรับเข้า/เบิกออกของสินค้านี้จะถูกลบทั้งหมด และไม่สามารถกู้คืนได้')"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=h($x['id'])?>"><input type="hidden" name="show" value="<?=h($show)?>"><button class="button danger" type="submit">ลบ</button></form><?php endif;?></td></tr><?php endforeach;?></table></div><?php page_end();
