<?php require_once __DIR__ . '/../src/partials.php'; $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){ check_csrf(); $action=$_POST['action']??''; try {
 if($action==='save') { $id=(int)($_POST['id']??0); $code=trim($_POST['code']??''); $name=trim($_POST['name']??''); $unit=trim($_POST['unit']??'pcs'); $min=max(0,(int)($_POST['min_stock']??0)); if(!$code||!$name) throw new Exception('กรุณากรอกรหัสและชื่อสินค้า'); if($id){$s=$pdo->prepare('UPDATE products SET code=?,name=?,unit=?,min_stock=?,updated_at=CURRENT_TIMESTAMP WHERE id=?');$s->execute([$code,$name,$unit,$min,$id]);flash('success','แก้ไขข้อมูลสินค้าแล้ว');}else{$s=$pdo->prepare('INSERT INTO products(code,name,unit,min_stock) VALUES(?,?,?,?)');$s->execute([$code,$name,$unit,$min]);flash('success','เพิ่มสินค้าแล้ว');}}
 elseif($action==='delete') { require_admin(); $id=(int)$_POST['id']; $s=$pdo->prepare('SELECT COUNT(*) FROM stock_movements WHERE product_id=?');$s->execute([$id]);if((int)$s->fetchColumn()>0) throw new Exception('ไม่สามารถลบสินค้าที่มีประวัติการเคลื่อนไหวได้');$s=$pdo->prepare('DELETE FROM products WHERE id=?');$s->execute([$id]);flash('success','ลบสินค้าแล้ว'); }
 header('Location:/products.php'); exit;
} catch(Throwable $e){flash('danger','ดำเนินการไม่สำเร็จ: '.$e->getMessage());header('Location:/products.php');exit;}}
$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM products WHERE id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}
$q=trim($_GET['q']??'');$s=$pdo->prepare('SELECT * FROM products WHERE code ILIKE ? OR name ILIKE ? ORDER BY name');$s->execute(['%'.$q.'%','%'.$q.'%']);$items=$s->fetchAll();page_start('คลังสินค้า');
?><div class="card"><form class="actions"><input name="q" placeholder="ค้นหาด้วยรหัสหรือชื่อสินค้า" value="<?=h($q)?>"><button class="primary">ค้นหา</button><?php if($q):?><a class="button secondary" href="/products.php">ล้างค้นหา</a><?php endif;?></form></div>
<div class="card form-card" style="margin-top:18px"><h3><?= $edit?'แก้ไขสินค้า':'เพิ่มสินค้า'?></h3><form method="post"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=h($edit['id']??0)?>"><div class="form-grid"><div><label>รหัสสินค้า</label><input name="code" value="<?=h($edit['code']??'')?>" required></div><div><label>ชื่อสินค้า</label><input name="name" value="<?=h($edit['name']??'')?>" required></div><div><label>หน่วย</label><input name="unit" value="<?=h($edit['unit']??'pcs')?>"></div><div><label>สต๊อกขั้นต่ำ</label><input type="number" name="min_stock" value="<?=h($edit['min_stock']??500)?>" min="0"></div></div><button class="primary"><?= $edit?'บันทึกการแก้ไข':'เพิ่มสินค้า'?></button><?php if($edit):?><a class="button secondary" href="/products.php">ยกเลิก</a><?php endif;?></form></div>
<div class="table-wrap"><table><tr><th>รหัส</th><th>สินค้า</th><th>หน่วย</th><th>คงเหลือ</th><th>ขั้นต่ำ</th><th>สถานะ</th><th>จัดการ</th></tr><?php foreach($items as $x):?><tr><td><?=h($x['code'])?></td><td><?=h($x['name'])?></td><td><?=h($x['unit'])?></td><td><?=number_format($x['current_stock'])?></td><td><?=number_format($x['min_stock'])?></td><td><?= $x['current_stock']<=$x['min_stock']?'<span class="badge danger-bg">ต่ำกว่าขั้นต่ำ</span>':'<span class="badge success-bg">ปกติ</span>'?></td><td class="actions"><a class="button secondary" href="?edit=<?=h($x['id'])?>">แก้ไข</a><?php if(is_admin()):?><form method="post" onsubmit="return confirm('ยืนยันการลบสินค้า?')"><input type="hidden" name="csrf" value="<?=h(csrf())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=h($x['id'])?>"><button class="button danger" type="submit">ลบ</button></form><?php endif;?></td></tr><?php endforeach;?></table></div><?php page_end();
